version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    build: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"