version: '3'

services:

  ean-api-redis:
    image: redis:7.0.11
    container_name: ean-api-redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - ean-api-redis-net

  ean-api-redisinsight:
    image: redislabs/redisinsight
    container_name: ean-api-redisinsight
    ports:
      - 9081:8001
    restart: unless-stopped
    networks:
      - ean-api-redis-net

networks:
  ean-api-redis-net: