version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: 'rabbitmq'
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_AUTH_BACKEND_URL=http://192.168.0.200:8080
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"

volumes:
  rabbitmq-volume:
