logging:
    level:
        com.prueba: trace
        org.springframework.security: info
        org.springframework.transaction: trace
spring:
    config:
        import: optional:file:api.env[.properties]
    datasource:
        initialization-mode: always
        driver-class-name: org.postgresql.Driver
        url: ${POSTGRES_DB_URL}
        username: ${POSTGRES_DB_USER}
        password: ${POSTGRES_DB_PASSWORD}
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_URL}
                    jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
    flyway:
        enabled: true

api:
    cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:}
        allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
        allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PATCH,PUT,DELETE,OPTIONS,HEAD}
        allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
        allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    keycloak:
        server-url: ${KEYCLOAK_URL}
        realm: ${KEYCLOAK_REALM}
        client-id: ${KEYCLOAK_CLIENT_ID}
        secret: ${KEYCLOAK_SECRET}
    cookie:
        http-only: true
        same-site: Strict
        secure: false
