logging:
    level:
        root: warn
spring:
    datasource:
        initialization-mode: always
        driver-class-name: org.postgresql.Driver
        url: ${POSTGRES_DB_URL}
        username: ${POSTGRES_DB_USER}
        password: ${POSTGRES_DB_PASSWORD}
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_URL}
                    jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
    flyway:
        enabled: false

api:
    cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:}
        allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
        allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PATCH,PUT,DELETE,OPTIONS,HEAD}
        allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
        allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    keycloak:
        server-url: ${KEYCLOAK_URL}
        realm: ${KEYCLOAK_REALM}
        client-id: ${KEYCLOAK_CLIENT_ID}
        secret: ${KEYCLOAK_SECRET}
    cookie:
        http-only: true
        same-site: Strict
        secure: false
