spring:
  config:
    import: optional:file:api.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
api:
  chat:
    broker:
      host: localhost
      port: 61613
      user: user
      password: password
