version: "3"

services:

  keycloak:
    image: bitnami/keycloak:21.1.1
    container_name: homeworkapp-keycloak
    ports:
      - "39080:8080"
    environment:
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloakdb
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=password
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_MANAGEMENT_USER=manager
      - KEYCLOAK_MANAGEMENT_PASSWORD=password
    restart: unless-stopped

  db:
    image: postgres:14.1-alpine
    container_name: homeworkapp-keycloak-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keycloakdb
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data