spring:
    application:
        name: homeworkapp
    datasource:
        initialization-mode: always
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:31500/homework_db
        username: pguser
        password: password
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
    profiles:
        active: test
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:39080/realms/homeworkapp}
                    jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:39080/realms/homeworkapp/protocol/openid-connect/certs}

server:
    port: 8080
    servlet:
        context-path: /api/v1

api:
    pagination:
        page-size: 10
    cors:
        allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
        allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PATCH,PUT,DELETE,OPTIONS,HEAD}
        allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
        allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    keycloak:
        server-url: ${KEYCLOAK_URL:http://localhost:39080}
        realm: ${KEYCLOAK_REALM:homeworkapp}
        client-id: ${KEYCLOAK_CLIENT_ID:homeworkapp}
        secret: ${KEYCLOAK_SECRET:secret}