spring:
    application:
        name: homeworkapp
    # Setup for MySQL:
    # spring.datasource.url = jdbc:mysql://localhost:3306/users
    # spring.datasource.username = USERNAME
    # spring.datasource.password = PASSWORD
    # spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
    # spring.jpa.hibernate.ddl-auto = update
    datasource:
        driver-class-name: org.h2.Driver
        username: a
        password: a
        url: "jdbc:h2:mem:homeworkapp;DB_CLOSE_ON_EXIT=FALSE"
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
    profiles:
        active: test

server:
    port: 8080
    # needed for swagger-ui to detect correct proxied paths correctly.
    # Configuration needed for the [Try out] buttons to work
    # this works in combination with the proxied headers
    # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # proxy_set_header X-Forwarded-Prefix /services/impower-facilioo;
    forward-headers-strategy: FRAMEWORK
 
springdoc:
    swagger-ui:
        # where the UI configuration is located at
        configUrl: /v3/api-docs/swagger-config
        filter: true
        deepLinking: true
        # where the server API yml/json files are at (dropdown in top right corner)
        urls[0]:
            url: /v3/api-docs
            name: backend