spring:
    application:
        name: homeworkapp
    data:
        jpa.repositories.enabled: true
    datasource:
        initialization-mode: always
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: homework-user
        password: postgres
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
    profiles:
        active: test

server:
    port: 8080