spring:
    application:
        name: homeworkapp
    datasource:
        initialization-mode: always
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:31500/postgres
        username: pguser
        password: password
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    profiles:
        active: test

server:
    port: 8080

api:
    pagination:
        page-size: 10
    cors:
        allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
        allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PATCH,PUT,DELETE,OPTIONS,HEAD}
        allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
        allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}