version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - KEYCLOAK_URL=https://localhost:39080
      - KEYCLOAK_REALM=homeworkapp
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"

volumes:
  rabbitmq-volume:
