version: "3"

services:

  ean-api-keycloak:
    image: bitnami/keycloak:21.1.1
    container_name: ean-api-keycloak
    ports:
      - "9080:8080"
    environment:
      - KEYCLOAK_DATABASE_HOST=ean-api-keycloak-db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=ean-api-keycloak-db
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=password
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_MANAGEMENT_USER=manager
      - KEYCLOAK_MANAGEMENT_PASSWORD=password
    restart: unless-stopped

  ean-api-keycloak-db:
    image: postgres:14.1-alpine
    container_name: ean-api-keycloak-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ean-api-keycloak-db
    restart: unless-stopped
    volumes:
      - ean-api-keycloak-db-volume:/var/lib/postgresql/data

volumes:
  ean-api-keycloak-db-volume:
