logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
spring:
  data:
    mongodb:
      database: "spike"
      auto-index-creation: false
      uri: "mongodb://admin:password@localhost:27017/"

mongock:
  migration-scan-package: com.spike.mongodb.changelogs
  transaction-enabled: false
  enabled: true
  track-ignored: false
